### PR TITLE
Feature/suspense edit forms and loading component

### PR DESCRIPTION
**Pull request by tobias-wiese**
## In this PR:
- The forms for course and account creation are now wrapped up in the FormSuspenseWrapper.vue, s.t. we can use suspense for loading the data of courses or accounts provided by the API into the forms
- Create a new component, that contains a loading animation and add it as fallback component to the suspense templates

## Reasons for Changes:
- we cannot just use the suspense tags in the forms themselves as suspense affects just components. Hence, we need a wrapper around it. I built a wrapper for both the account and the course forms, that shows the desired component. The form files themselves are adapted in that way, that the loadCourse/Account function is now normal code within the now async setup method, this way suspense can work with the async component. The beforeRouteEnter navigation guard is now implemented in the wrapper because it does not work within a subcomponent.
- some moving loading animation is fancier than just a simple label. Additionally, we now have a default loading component that can be used and adapted within the whole application 

## Notes:
You may look at the navigation guard. I am not sure, whether there my be a better way to realise that

### CODE REVIEW

**Comment by tobias-wiese** [comment]
We encountered problems regarding the navigation guards. I implemented them now in the wrapper component for the account form using 2 v-models (as it is working in Vue3) and emitting changes to success and hasInput. I will implement that for the course form later.

**Comment by tobias-wiese** [comment]
>     * Maybe we should also talk about the prop naming, why is the prop called "successComp"? It is a boolean, not a component

I renamed them and removed the unnecessary prop declaration

**Comment by tobias-wiese** [comment]
@bastihav all suggested improvements should be implemented now.
@theovier the PR is now ready to be reviewed

**Comment by theovier** [comment]
Please consider removing the debug console logs.

**Comment by tobias-wiese** [comment]
> 
> 
> Please consider removing the debug console logs.

done.

**Pull request merged**
